# Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: <%=ENV['REDIS_URL']%>

development:
  adapter: redis
  url: <%=ENV['REDIS_URL']%>

test:
  url: redis://localhost:6379/3
